### ISSUE TITLE
Please read this issue and respond

### ISSUE THREAD

**Issue by ClaireWolfe** [ClaireWolfe/test#3]
Hi Kevin,

I am trying out an issue in GitHub.  I will try to assign this to you and see if you can respond.

If this works, we can say we understand issues :)

Claire

**Comment by burnskd** [comment]
Hi Claire

I reject your issue!

**Comment by burnskd** [comment]
closing issue

**Comment by burnskd** [comment]
i said i'm closing this issue!

**Comment by ClaireWolfe** [comment]
Oh yeah, I reject your rejection!

I say we know how to create and close issues.  DONE!
